name: Check latest Lens version

on:
  schedule:
    - cron: "15 */6 * * *"
  workflow_dispatch:

jobs:
  version_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # with:
        #   token: ${{ secrets.PAT }}
      - name: Get the latest version of Lens
        run: |
          curl -s https://lens-binaries.s3.amazonaws.com/ide/latest-mac.yml |\
            grep -o "version:.*-latest" | grep -oP "(\d+(:?\.\d+)+)" |\
            head -n 1 > version
          export LENS_VERSION=$(cat version)
          echo "LENS_VERSION=$LENS_VERSION" >> $GITHUB_ENV
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.0.0
        with:
          message: "Version updated to: ${{ env.LENS_VERSION }}"
